# Generated by Django 5.0.7 on 2024-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_income_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
