# Generated by Django 5.0.7 on 2024-07-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_income_owner_alter_income_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
