# Generated by Django 5.0.7 on 2024-07-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_fullname_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullName',
        ),
    ]
